* Pluralbug 🐞: A Pluralkit for Matrix
  This project intends to port [[https://pluralkit.me/][pluralkit]] to [[https://matrix.org/][Matrix]]. Pluralbug is a bot that can be invited into a room in Matrix. It keeps track of custom display names and their associated profile images and fronts specified messages with the custom system members information, allowing a system to present and maintain multiple "pseudo-accounts" under one Matrix user.
** nio-template
   The implementation of Pluralbug is based on the [[https://github.com/anoadragon453/nio-template][nio-template]] project by github user anoadragon453, which is a template for creating bots with the [[https://github.com/poljar/matrix-nio][matrix-nio]] Matrix client library. Thank you for your contribution to this software. More information on the specifics of implementation can be found in the documentation of that project, and by the [[https://matrix-nio.readthedocs.io/en/latest/#api-documentation][documentation]] for matrix-nio.
** Setup
   1. Create a copy of ~sample.config.yaml~ named ~config.yaml~.
   2. Change the ~user_id~, ~user_password~ and ~homeserver_url~ and other relevant information in ~config.yaml~.
   3. Follow the installation instructions for nio-template as they pertain to this repository. In so doing, creating a python virtual environment.
   4. With this virtual environment activated, change to the project directory and execute the ~pluralbug~ command.
   5. Invite the pluralbug user to a matrix room.
** Bot Commands
   Customize the bot commands to your convenience in ~config.yaml~.
   - The default command prefix for pluralbug is ~-p~. This can be changed in ~config.yaml~.
   - "-p sw" for "switch". Example: "-p sw"
     - "-p sw name /path/to/file" switches user and changes pfp simultaneously.
     - "-p sw name" switches user only. Previously updated pfp associated with that user will be changed also. If no image has been set for that user, then the pfp will be default.
   - "-p re" for "react". Example "-p re ⭐"
   - "-p del" for "delete". Example "-p del <message>" will immediately delete its own message. Used mainly for testing purposes.
   - "-p r" for "replace". This is usually the most common command to be used. Example "-p r <message>" will delete this message and replace it with one sent by pluralbug containing the same text. 
   - "-p help" to display options.
   - "-p pfp" to change profile picture. Currently only .png images are accepted. Example:
     - "-p pfp name /path/to/file/" will change the profile picture for the current (pseudo) user.
